### ISSUE TITLE
MISSING - Segmented Sieve and Linear Time Sieve

### ISSUE THREAD

**Issue by ks-amit** [likecs/Competitive-Coding#7]
https://github.com/dumbape/Competitive-Programming/blob/master/Sieve.cpp

**Comment by likecs** [comment]
@dumbape , all the implementations you wrote in the headings are available [here](https://github.com/likecs/Competitive-Coding/blob/master/C%2B%2B14/Maths/Modular%20arithmetic/prime_sieve.cpp). The only thing which I found extra in your code is regarding sum/product of divisors. The segmented sieve code of yours is not optimised and uses unnecessary if statements and no comments regarding calling the sive function before so that "pr" vector is correctly initialised. 

I am closing this issue now. You can create a pull request for the sum of divisors things but before doing so, refer to the [contributing guidelines](https://github.com/likecs/Competitive-Coding/blob/master/guidlines.md)
