### ISSUE TITLE
STL commands

### ISSUE THREAD

**Issue by aryanc403** [likecs/Competitive-Coding#9]
I can add commands of STL containers, which can be helpful for newbie. That what are the commands for particular container.

**Comment by likecs** [comment]
Hi aryanc403,
This is not required as this repository concentrates on adding tempates on generally found in language documentation. This can easily be looked up on the language documentation and such things should be read from there as they clearly state what is required and expected behaviour covering all possible scenarios. Links to such things is not meant to be part of this repository. There are other repository which contain links to useful documentations/sources to such language specific modules. You can add it there.

Closing this issue.
